# Configuration file
models:
  whisper_model: "base"
  tts_model: "tts_models/en/ljspeech/tacotron2-DDC"

vad:
  mode: 2
  sample_rate: 16000
  frame_duration_ms: 30
  silence_threshold_ms: 1000

logging:
  level: INFO
  file: logs/beda.log
